services:
  cpu-service:
    build: .
    image: cpu-service:latest
    container_name: cpu-service
    ports:
      - "5001:5001"
    pid: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - .:/app   # 整個專案目錄 mount 進 container 的 /app
    restart: unless-stopped
